@extends('layouts.app')
@section('title', 'Kelola Jadwal')
@section('content')
<div class="page-title"><div><p class="eyebrow">Petugas puskesmas</p><h1>Jadwal & kapasitas</h1><p>Anda hanya dapat mengelola layanan di {{ auth()->user()->puskesmas?->nama_puskesmas ?? 'puskesmas yang ditetapkan admin' }}.</p></div><a class="button secondary" href="{{ route('officer.queues.index') }}">Kelola antrean</a></div>
<section class="panel"><h2>Tambah jadwal</h2><form method="post" action="{{ route('officer.schedules.store') }}" class="form-grid">@csrf
    <label class="span-2">Layanan<select name="layanan_id" required><option value="">Pilih layanan</option>@foreach ($services as $service)<option value="{{ $service->layanan_id }}">{{ $service->nama_layanan }}</option>@endforeach</select></label>
    <label>Nama dokter<input name="nama_dokter" maxlength="1000" placeholder="Opsional"></label><label>Spesialisasi<input name="spesialisasi" maxlength="1000" placeholder="Opsional"></label>
    <label>Hari<select name="hari" required>@foreach (['SENIN','SELASA','RABU','KAMIS','JUMAT','SABTU','MINGGU'] as $day)<option>{{ $day }}</option>@endforeach</select></label>
    <label>Kapasitas<input type="number" name="kapasitas" value="50" min="1" max="1000" required></label>
    <label>Jam buka<input type="time" name="jam_buka" value="08:00" required></label><label>Jam tutup<input type="time" name="jam_tutup" value="12:00" required></label>
    <input type="hidden" name="status" value="AKTIF"><button class="button primary" type="submit">Simpan jadwal</button>
</form></section>
<section><div class="section-heading"><div><p class="eyebrow">Daftar jadwal</p><h2>{{ $schedules->count() }} jadwal</h2></div></div><div class="stack-list">
@forelse ($schedules as $schedule)<article class="record"><div><span class="status {{ strtolower($schedule->status) }}">{{ $schedule->status }}</span><h3>{{ $schedule->service->nama_layanan }}</h3><p>{{ $schedule->puskesmas->nama_puskesmas }} · {{ $schedule->hari }} · {{ substr($schedule->jam_buka,0,5) }}–{{ substr($schedule->jam_tutup,0,5) }} · kapasitas {{ $schedule->kapasitas }} · {{ $schedule->nama_dokter ?: 'Dokter belum diatur' }}</p></div><details><summary>Edit</summary><form method="post" action="{{ route('officer.schedules.update', $schedule) }}" class="inline-form">@csrf @method('put')<select name="layanan_id" required>@foreach($services as $service)<option value="{{ $service->layanan_id }}" @selected($schedule->layanan_id === $service->layanan_id)>{{ $service->nama_layanan }}</option>@endforeach</select><input name="nama_dokter" value="{{ $schedule->nama_dokter }}" placeholder="Nama dokter"><input name="spesialisasi" value="{{ $schedule->spesialisasi }}" placeholder="Spesialisasi"><select name="hari">@foreach (['SENIN','SELASA','RABU','KAMIS','JUMAT','SABTU','MINGGU'] as $day)<option @selected($schedule->hari===$day)>{{ $day }}</option>@endforeach</select><input type="time" name="jam_buka" value="{{ substr($schedule->jam_buka,0,5) }}"><input type="time" name="jam_tutup" value="{{ substr($schedule->jam_tutup,0,5) }}"><input type="number" name="kapasitas" value="{{ $schedule->kapasitas }}"><select name="status"><option @selected($schedule->status==='AKTIF')>AKTIF</option><option @selected($schedule->status==='NONAKTIF')>NONAKTIF</option></select><button class="button primary">Simpan</button></form><form method="post" action="{{ route('officer.schedules.destroy', $schedule) }}">@csrf @method('delete')<button class="button danger">Hapus jadwal</button></form></details></article>@empty <div class="empty">Belum ada jadwal.</div>@endforelse
</div></section>
@endsection
