@extends('layouts.app')
@section('title', 'Kelola Antrean')
@section('content')
<div class="page-title"><div><p class="eyebrow">CRUD transaksi</p><h1>Data antrean</h1><p>Ubah status secara manual. Tidak ada loket, sesi, snapshot, atau real-time otomatis.</p></div><a class="button secondary" href="{{ route('officer.schedules.index') }}">Kelola jadwal</a></div>
<section class="panel"><h2>Tambah antrean manual</h2><form method="post" action="{{ route('officer.queues.store') }}" class="form-grid">@csrf
    <label>Masyarakat<select name="nik" required><option value="">Pilih NIK</option>@foreach($citizens as $citizen)<option value="{{ $citizen->nik }}">{{ $citizen->nik }} · {{ $citizen->nama_lengkap }}</option>@endforeach</select></label>
    <label>Jadwal<select name="jadwal_id" required><option value="">Pilih jadwal</option>@foreach($schedules as $schedule)<option value="{{ $schedule->jadwal_id }}">{{ $schedule->puskesmasService->puskesmas->nama_puskesmas }} · {{ $schedule->puskesmasService->service->nama_layanan }} · {{ $schedule->hari }}</option>@endforeach</select></label>
    <label>Tanggal<input type="date" name="tanggal_daftar" value="{{ today()->toDateString() }}" required></label><input type="hidden" name="status_antrean" value="WAITING"><button class="button primary">Tambah antrean</button>
</form></section>
<section><div class="section-heading"><div><p class="eyebrow">Transaksi tersimpan</p><h2>{{ $queues->count() }} antrean</h2></div></div><div class="stack-list">
@forelse($queues as $queue)<article class="queue-card"><div class="queue-number">{{ str_pad($queue->nomor_antrean,3,'0',STR_PAD_LEFT) }}</div><div><span class="status {{ strtolower($queue->status_antrean) }}">{{ $queue->status_antrean }}</span><h3>{{ $queue->citizen->nama_lengkap }}</h3><p>{{ $queue->schedule->puskesmasService->puskesmas->nama_puskesmas }} · {{ $queue->schedule->puskesmasService->service->nama_layanan }} · {{ $queue->tanggal_daftar->format('d-m-Y') }}</p></div><div class="actions"><form method="post" action="{{ route('officer.queues.update',$queue) }}" class="inline-form">@csrf @method('patch')<select name="status_antrean">@foreach(['WAITING','CALLED','SERVING','COMPLETED','CANCELLED'] as $status)<option @selected($queue->status_antrean===$status)>{{ $status }}</option>@endforeach</select><button class="button secondary">Ubah</button></form><form method="post" action="{{ route('officer.queues.destroy',$queue) }}">@csrf @method('delete')<button class="button danger">Hapus</button></form></div></article>@empty<div class="empty">Belum ada antrean.</div>@endforelse
</div></section>
@endsection
