@extends('layouts.app')
@section('title', 'Data Master')
@section('content')
<div class="page-title"><div><p class="eyebrow">Admin / Dinas Kesehatan</p><h1>Data master UTS</h1><p>Kelola hanya empat master dan satu relasi. Jadwal dikerjakan petugas.</p></div><a class="button secondary" href="{{ route('officer.schedules.index') }}">Lihat jadwal</a></div>
<nav class="tabs" aria-label="Kategori data">
    <a href="#masyarakat" data-master-tab="masyarakat">Masyarakat</a><a href="#akun" data-master-tab="akun">Petugas & akun</a><a href="#puskesmas" data-master-tab="puskesmas">Puskesmas</a><a href="#layanan" data-master-tab="layanan">Layanan</a><a href="#relasi" data-master-tab="relasi">Relasi layanan</a>
</nav>

<section id="masyarakat" data-master-panel class="panel-section active"><div class="section-heading"><div><p class="eyebrow">Data dari Dinkes</p><h2>Masyarakat</h2><p>NIK yang belum memiliki akun dapat dipakai pada halaman aktivasi.</p></div><span class="count">{{ $citizens->count() }} data</span></div>
    <div class="split"><form method="post" action="{{ route('admin.citizens.store') }}" class="panel form-grid one">@csrf<h3>Tambah masyarakat</h3><label>NIK<input name="nik" maxlength="16" required></label><label>Nama lengkap<input name="nama_lengkap" required></label><label>Nomor telepon<input name="nomor_telepon"></label><label>Alamat<textarea name="alamat"></textarea></label><input type="hidden" name="status_data" value="AKTIF"><button class="button primary">Simpan masyarakat</button></form>
    <div class="stack-list">@foreach($citizens as $citizen)<article class="record"><div><span class="status {{ strtolower($citizen->status_data) }}">{{ $citizen->status_data }}</span><h3>{{ $citizen->nama_lengkap }}</h3><p>{{ $citizen->nik }} · {{ $citizen->account ? 'Sudah aktivasi' : 'Belum aktivasi' }}</p></div><details><summary>Edit</summary><form method="post" action="{{ route('admin.citizens.update',$citizen) }}" class="inline-form">@csrf @method('put')<input name="nik" value="{{ $citizen->nik }}" readonly><input name="nama_lengkap" value="{{ $citizen->nama_lengkap }}" required><input name="nomor_telepon" value="{{ $citizen->nomor_telepon }}"><input name="alamat" value="{{ $citizen->alamat }}"><select name="status_data"><option @selected($citizen->status_data==='AKTIF')>AKTIF</option><option @selected($citizen->status_data==='NONAKTIF')>NONAKTIF</option></select><button class="button primary">Simpan</button></form><form method="post" action="{{ route('admin.citizens.destroy',$citizen) }}">@csrf @method('delete')<button class="button danger">Hapus</button></form></details></article>@endforeach</div></div>
</section>

<section id="akun" data-master-panel class="panel-section"><div class="section-heading"><div><p class="eyebrow">Akun internal</p><h2>Petugas & akun</h2><p>Masyarakat membuat akun sendiri melalui aktivasi NIK.</p></div><span class="count">{{ $accounts->count() }} akun</span></div>
    <div class="split"><form method="post" action="{{ route('admin.officers.store') }}" class="panel form-grid one">@csrf<h3>Tambah petugas</h3><label>Nama lengkap<input name="nama_lengkap" required></label><label>Email<input type="email" name="email" required></label><label>Password<input type="password" name="password" minlength="8" required></label><label>Puskesmas<select name="puskesmas_id" required><option value="">Pilih</option>@foreach($puskesmasItems as $item)<option value="{{ $item->puskesmas_id }}">{{ $item->nama_puskesmas }}</option>@endforeach</select></label><button class="button primary">Simpan petugas</button></form>
    <div class="stack-list">@foreach($accounts as $account)<article class="record"><div><span class="status {{ strtolower($account->status_akun) }}">{{ $account->role }} · {{ $account->status_akun }}</span><h3>{{ $account->nama_lengkap }}</h3><p>{{ $account->email }}{{ $account->puskesmas ? ' · '.$account->puskesmas->nama_puskesmas : '' }}</p></div><details><summary>Edit</summary><form method="post" action="{{ route('admin.accounts.update',$account) }}" class="inline-form">@csrf @method('put')<input name="nama_lengkap" value="{{ $account->nama_lengkap }}" required><input type="email" name="email" value="{{ $account->email }}" required><select name="puskesmas_id"><option value="">Tanpa puskesmas</option>@foreach($puskesmasItems as $item)<option value="{{ $item->puskesmas_id }}" @selected($account->puskesmas_id===$item->puskesmas_id)>{{ $item->nama_puskesmas }}</option>@endforeach</select><select name="status_akun"><option @selected($account->status_akun==='AKTIF')>AKTIF</option><option @selected($account->status_akun==='NONAKTIF')>NONAKTIF</option></select><input type="password" name="password" placeholder="Password baru (opsional)"><button class="button primary">Simpan</button></form>@if(!in_array($account->role,['MASYARAKAT']) && !auth()->user()->is($account))<form method="post" action="{{ route('admin.accounts.destroy',$account) }}">@csrf @method('delete')<button class="button danger">Hapus akun</button></form>@endif</details></article>@endforeach</div></div>
</section>

<section id="puskesmas" data-master-panel class="panel-section"><div class="section-heading"><div><p class="eyebrow">Data master</p><h2>Puskesmas</h2></div><span class="count">{{ $puskesmasItems->count() }} data</span></div>
    <div class="split"><form method="post" action="{{ route('admin.puskesmas.store') }}" class="panel form-grid one">@csrf<h3>Tambah puskesmas</h3><label>Nama<input name="nama_puskesmas" required></label><label>Alamat<textarea name="alamat" required></textarea></label><label>Nomor telepon<input name="nomor_telepon"></label><input type="hidden" name="status" value="AKTIF"><button class="button primary">Simpan puskesmas</button></form>
    <div class="stack-list">@foreach($puskesmasItems as $item)<article class="record"><div><span class="status {{ strtolower($item->status) }}">{{ $item->status }}</span><h3>{{ $item->nama_puskesmas }}</h3><p>{{ $item->alamat }} · {{ $item->puskesmas_services_count }} layanan · {{ $item->officers_count }} petugas</p></div><details><summary>Edit</summary><form method="post" action="{{ route('admin.puskesmas.update',$item) }}" class="inline-form">@csrf @method('put')<input name="nama_puskesmas" value="{{ $item->nama_puskesmas }}" required><input name="alamat" value="{{ $item->alamat }}" required><input name="nomor_telepon" value="{{ $item->nomor_telepon }}"><select name="status"><option @selected($item->status==='AKTIF')>AKTIF</option><option @selected($item->status==='NONAKTIF')>NONAKTIF</option></select><button class="button primary">Simpan</button></form><form method="post" action="{{ route('admin.puskesmas.destroy',$item) }}">@csrf @method('delete')<button class="button danger">Hapus</button></form></details></article>@endforeach</div></div>
</section>

<section id="layanan" data-master-panel class="panel-section"><div class="section-heading"><div><p class="eyebrow">Data master</p><h2>Layanan</h2></div><span class="count">{{ $services->count() }} data</span></div>
    <div class="split"><form method="post" action="{{ route('admin.services.store') }}" class="panel form-grid one">@csrf<h3>Tambah layanan</h3><label>Nama layanan<input name="nama_layanan" required></label><label>Deskripsi<textarea name="deskripsi"></textarea></label><input type="hidden" name="status" value="AKTIF"><button class="button primary">Simpan layanan</button></form>
    <div class="stack-list">@foreach($services as $service)<article class="record"><div><span class="status {{ strtolower($service->status) }}">{{ $service->status }}</span><h3>{{ $service->nama_layanan }}</h3><p>{{ $service->deskripsi }} · {{ $service->puskesmas_services_count }} puskesmas</p></div><details><summary>Edit</summary><form method="post" action="{{ route('admin.services.update',$service) }}" class="inline-form">@csrf @method('put')<input name="nama_layanan" value="{{ $service->nama_layanan }}" required><input name="deskripsi" value="{{ $service->deskripsi }}"><select name="status"><option @selected($service->status==='AKTIF')>AKTIF</option><option @selected($service->status==='NONAKTIF')>NONAKTIF</option></select><button class="button primary">Simpan</button></form><form method="post" action="{{ route('admin.services.destroy',$service) }}">@csrf @method('delete')<button class="button danger">Hapus</button></form></details></article>@endforeach</div></div>
</section>

<section id="relasi" data-master-panel class="panel-section"><div class="section-heading"><div><p class="eyebrow">N : M</p><h2>Puskesmas · layanan</h2></div><span class="count">{{ $relations->count() }} relasi</span></div>
    <div class="split"><form method="post" action="{{ route('admin.relations.store') }}" class="panel form-grid one">@csrf<h3>Hubungkan layanan</h3><label>Puskesmas<select name="puskesmas_id" required>@foreach($puskesmasItems as $item)<option value="{{ $item->puskesmas_id }}">{{ $item->nama_puskesmas }}</option>@endforeach</select></label><label>Layanan<select name="layanan_id" required>@foreach($services as $service)<option value="{{ $service->layanan_id }}">{{ $service->nama_layanan }}</option>@endforeach</select></label><input type="hidden" name="status" value="AKTIF"><button class="button primary">Hubungkan</button></form>
    <div class="stack-list">@foreach($relations as $relation)<article class="record"><div><span class="status {{ strtolower($relation->status) }}">{{ $relation->status }}</span><h3>{{ $relation->service->nama_layanan }}</h3><p>{{ $relation->puskesmas->nama_puskesmas }} · {{ $relation->schedules_count }} jadwal</p></div><details><summary>Edit</summary><form method="post" action="{{ route('admin.relations.update',$relation) }}" class="inline-form">@csrf @method('put')<input type="hidden" name="puskesmas_id" value="{{ $relation->puskesmas_id }}"><input type="hidden" name="layanan_id" value="{{ $relation->layanan_id }}"><select name="status"><option @selected($relation->status==='AKTIF')>AKTIF</option><option @selected($relation->status==='NONAKTIF')>NONAKTIF</option></select><button class="button primary">Simpan</button></form><form method="post" action="{{ route('admin.relations.destroy',$relation) }}">@csrf @method('delete')<button class="button danger">Hapus relasi</button></form></details></article>@endforeach</div></div>
</section>
@endsection
